/**
 * HackRadar India — Client-Side Controller
 * Handles real-time search, multi-faceted filtering, countdown ticker calculation,
 * calendar export, and community submissions.
 */

// Application State
const state = {
  hackathons: [],
  filtered: [],
  filters: {
    search: '',
    mode: 'ALL',
    city: 'ALL',
    tag: 'ALL',
    sort: 'deadline_asc'
  },
  lastSynced: null
};

// DOM Elements
const elements = {
  cardsGrid: document.getElementById('cardsGrid'),
  loadingState: document.getElementById('loadingState'),
  emptyState: document.getElementById('emptyState'),
  resultsCount: document.getElementById('resultsCount'),
  totalCount: document.getElementById('totalCount'),
  onlineCount: document.getElementById('onlineCount'),
  offlineCount: document.getElementById('offlineCount'),
  syncStatus: document.getElementById('syncStatus'),
  searchInput: document.getElementById('searchInput'),
  clearSearchBtn: document.getElementById('clearSearchBtn'),
  modeTabs: document.querySelectorAll('.mode-tab'),
  citySelect: document.getElementById('citySelect'),
  sortSelect: document.getElementById('sortSelect'),
  tagsContainer: document.getElementById('tagsContainer'),
  resetFiltersBtn: document.getElementById('resetFiltersBtn'),
  submitModal: document.getElementById('submitModal'),
  openSubmitModalBtn: document.getElementById('openSubmitModalBtn'),
  closeSubmitModalBtn: document.getElementById('closeSubmitModalBtn'),
  cancelSubmitModalBtn: document.getElementById('cancelSubmitModalBtn'),
  submitEventForm: document.getElementById('submitEventForm'),
  toast: document.getElementById('toast'),
  syncNowLink: document.getElementById('syncNowLink')
};

// --- Initialization ---
document.addEventListener('DOMContentLoaded', () => {
  initEventListeners();
  loadHackathonData();
  // Refresh countdowns every 60 seconds
  setInterval(renderCards, 60000);
});

// --- Data Loading ---
async function loadHackathonData() {
  try {
    elements.loadingState.style.display = 'flex';
    elements.cardsGrid.innerHTML = '';
    elements.emptyState.style.display = 'none';

    // Fetch snapshot generated by the automated Python pipeline
    const response = await fetch('data/hackathons.json?t=' + Date.now());
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}`);
    }

    const data = await response.json();
    state.hackathons = data.hackathons || [];
    state.lastSynced = data.last_synced_at;

    // Load any community-submitted items from localStorage
    const localSubmissions = JSON.parse(localStorage.getItem('hackradar_user_submissions') || '[]');
    if (localSubmissions.length > 0) {
      state.hackathons = [...localSubmissions, ...state.hackathons];
    }

    updateMetrics();
    applyFilters();

    if (state.lastSynced) {
      const syncDate = new Date(state.lastSynced);
      const timeStr = syncDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
      elements.syncStatus.innerHTML = `<span class="sync-dot"></span><span class="sync-text">Synced today at ${timeStr}</span>`;
    }
  } catch (err) {
    console.warn('Fallback to embedded dataset due to fetch limitation:', err);
    useFallbackData();
  } finally {
    elements.loadingState.style.display = 'none';
  }
}

// Fallback seed data in case of offline file access
function useFallbackData() {
  state.hackathons = [
    {
      source: "Devfolio",
      source_url: "https://hackodisha.devfolio.co",
      title: "HackOdisha 5.0",
      organizer: "NIT Rourkela & Webwiz",
      mode: "Hybrid",
      venue_address: "NIT Rourkela Campus, Odisha / Online Discord",
      city: "Rourkela",
      banner_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-09-05T23:59:59Z",
      prize_pool: "₹5,00,000",
      tags: ["AI/ML", "Web3", "FinTech", "Student Track"]
    },
    {
      source: "Unstop",
      source_url: "https://unstop.com/hackathons/smart-india-hackathon-2026",
      title: "Smart India Hackathon (SIH 2026)",
      organizer: "Ministry of Education & AICTE",
      mode: "Hybrid",
      venue_address: "Nodal Centers Nationwide (IITs, NITs) & Online Portal",
      city: "All India (Nodal Hubs)",
      banner_url: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-09-10T23:59:59Z",
      prize_pool: "₹1,00,00,000+",
      tags: ["National", "GovTech", "Hardware & Software"]
    },
    {
      source: "Unstop",
      source_url: "https://unstop.com/hackathons/srm-hack-a-revolution-2026",
      title: "SRM HackARev 2026",
      organizer: "SRM University AP",
      mode: "Offline",
      venue_address: "Neerukonda Campus, Mangalagiri, Amaravati, Andhra Pradesh",
      city: "Amaravati",
      banner_url: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-09-28T23:59:59Z",
      prize_pool: "₹2,50,000",
      tags: ["AI Agents", "Cloud Native", "EdTech", "IoT"]
    },
    {
      source: "Devfolio",
      source_url: "https://hackinout.devfolio.co",
      title: "Hack InOut 2026",
      organizer: "InOut Community",
      mode: "Offline",
      venue_address: "Koramangala Tech Park, Bengaluru, Karnataka",
      city: "Bengaluru",
      banner_url: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-10-01T23:59:59Z",
      prize_pool: "₹10,00,000",
      tags: ["Full Stack", "Distributed Systems", "AI Agents"]
    },
    {
      source: "Devfolio",
      source_url: "https://ethindia2026.devfolio.co",
      title: "ETHIndia 2026",
      organizer: "Devfolio & Ethereum Foundation",
      mode: "Offline",
      venue_address: "KTPO Convention Centre, Whitefield, Bengaluru, Karnataka",
      city: "Bengaluru",
      banner_url: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-11-15T23:59:59Z",
      prize_pool: "$150,000+ (₹1.25 Cr)",
      tags: ["Web3", "Solidity", "Zero Knowledge", "DeFi"]
    },
    {
      source: "Google Developers",
      source_url: "https://developers.google.com/community/gdsc-solution-challenge",
      title: "Google Solution Challenge 2026",
      organizer: "Google Developer Student Clubs",
      mode: "Online",
      venue_address: "Virtual / Google Cloud Platform",
      city: "Online",
      banner_url: "https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&w=800&q=80",
      deadline: "2026-10-15T23:59:59Z",
      prize_pool: "$40,000 + Google Mentorship",
      tags: ["AI/ML", "Google Cloud", "UN SDGs"]
    }
  ];
  updateMetrics();
  applyFilters();
}

// --- Metrics & Counters ---
function updateMetrics() {
  const total = state.hackathons.length;
  const online = state.hackathons.filter(h => h.mode === 'Online').length;
  const offline = state.hackathons.filter(h => h.mode === 'Offline' || h.mode === 'Hybrid').length;

  elements.totalCount.textContent = total;
  elements.onlineCount.textContent = online;
  elements.offlineCount.textContent = offline;
}

// --- Filter Engine ---
function applyFilters() {
  const { search, mode, city, tag, sort } = state.filters;
  const query = search.trim().toLowerCase();

  state.filtered = state.hackathons.filter(item => {
    // 1. Search Query Match
    if (query) {
      const matchTitle = (item.title || '').toLowerCase().includes(query);
      const matchOrg = (item.organizer || '').toLowerCase().includes(query);
      const matchVenue = (item.venue_address || '').toLowerCase().includes(query);
      const matchTags = (item.tags || []).some(t => t.toLowerCase().includes(query));
      if (!matchTitle && !matchOrg && !matchVenue && !matchTags) return false;
    }

    // 2. Mode Match
    if (mode !== 'ALL' && item.mode !== mode) {
      return false;
    }

    // 3. City Match
    if (city !== 'ALL') {
      if (city === 'Online' && item.mode !== 'Online') return false;
      if (city !== 'Online') {
        const itemCity = (item.city || '').toLowerCase();
        const itemVenue = (item.venue_address || '').toLowerCase();
        const targetCity = city.toLowerCase();
        if (!itemCity.includes(targetCity) && !itemVenue.includes(targetCity)) return false;
      }
    }

    // 4. Tag Match
    if (tag !== 'ALL') {
      const hasTag = (item.tags || []).some(t => t.toLowerCase().includes(tag.toLowerCase()));
      if (!hasTag) return false;
    }

    return true;
  });

  // Sorting
  state.filtered.sort((a, b) => {
    if (sort === 'deadline_asc') {
      return new Date(a.deadline || '2099-01-01') - new Date(b.deadline || '2099-01-01');
    } else if (sort === 'start_asc') {
      return new Date(a.start_date || '2099-01-01') - new Date(b.start_date || '2099-01-01');
    } else if (sort === 'title_asc') {
      return (a.title || '').localeCompare(b.title || '');
    }
    return 0;
  });

  elements.resultsCount.textContent = state.filtered.length;
  renderCards();
}

// --- Card Rendering ---
function renderCards() {
  const container = elements.cardsGrid;
  container.innerHTML = '';

  if (state.filtered.length === 0) {
    elements.emptyState.style.display = 'flex';
    return;
  }
  elements.emptyState.style.display = 'none';

  const now = new Date();

  state.filtered.forEach((h, index) => {
    const card = document.createElement('article');
    card.className = 'hackathon-card';
    card.style.animationDelay = `${index * 50}ms`;

    // Mode Badge Class & Icon
    let modeClass = 'badge-offline';
    let modeIcon = '📍 In-Person';
    let addressIcon = '🏛️';

    if (h.mode === 'Online') {
      modeClass = 'badge-online';
      modeIcon = '🌐 Online';
      addressIcon = '💻';
    } else if (h.mode === 'Hybrid') {
      modeClass = 'badge-hybrid';
      modeIcon = '🔀 Hybrid';
      addressIcon = '🌐/🏛️';
    }

    // Countdown calculation
    const deadlineDate = h.deadline ? new Date(h.deadline) : null;
    let countdownText = 'Open Registration';
    let isUrgent = false;

    if (deadlineDate && !isNaN(deadlineDate.getTime())) {
      const diffMs = deadlineDate - now;
      if (diffMs < 0) {
        countdownText = 'Registration Closed';
      } else {
        const days = Math.floor(diffMs / (1000 * 60 * 60 * 24));
        const hours = Math.floor((diffMs % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        if (days > 0) {
          countdownText = `${days}d ${hours}h left`;
          if (days <= 5) isUrgent = true;
        } else {
          countdownText = `${hours}h left!`;
          isUrgent = true;
        }
      }
    }

    // Tag Badges
    const tagsHtml = (h.tags || ['Tech', 'Hackathon'])
      .slice(0, 3)
      .map(t => `<span class="tag-badge">#${t}</span>`)
      .join('');

    card.innerHTML = `
      <div class="card-banner-wrapper">
        <img 
          src="${h.banner_url || 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80'}" 
          alt="${h.title}" 
          class="card-banner-img"
          loading="lazy"
          onerror="this.src='https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80'"
        />
        <span class="badge-mode ${modeClass}">${modeIcon}</span>
        <span class="badge-source">${h.source || 'Aggregated'}</span>
      </div>

      <div class="card-body">
        <h3 class="card-title" title="${h.title}">${h.title}</h3>
        <p class="card-organizer">by ${h.organizer || 'Indian Tech Community'}</p>

        <div class="card-address-box">
          <span class="address-icon">${addressIcon}</span>
          <span class="address-text" title="${h.venue_address || 'India'}">
            ${h.venue_address || 'Check official event link for venue details'}
          </span>
        </div>

        <div class="card-meta-row">
          <div class="prize-box">
            <span class="prize-lbl">Prize Pool</span>
            <span class="prize-val">${h.prize_pool || 'Prizes & Swag'}</span>
          </div>
          <div class="countdown-box">
            <span class="countdown-lbl">Deadline</span>
            <span class="countdown-val" style="color: ${isUrgent ? 'var(--accent-rose)' : 'var(--accent-emerald)'}">
              ${countdownText}
            </span>
          </div>
        </div>

        <div class="card-tags">
          ${tagsHtml}
        </div>

        <div class="card-actions">
          <a 
            href="${h.source_url}" 
            target="_blank" 
            rel="noopener noreferrer" 
            class="btn-apply"
          >
            Apply on ${h.source || 'Platform'} →
          </a>
          <button 
            class="btn-cal" 
            title="Add to Google Calendar"
            onclick="addToGoogleCalendar('${encodeURIComponent(h.title)}', '${encodeURIComponent(h.venue_address || '')}', '${h.deadline || ''}', '${encodeURIComponent(h.source_url)}')"
          >
            📅
          </button>
        </div>
      </div>
    `;

    container.appendChild(card);
  });
}

// --- Google Calendar Quick Link ---
window.addToGoogleCalendar = function(title, venue, deadline, url) {
  const eventTitle = decodeURIComponent(title);
  const eventDetails = `Registration deadline for ${eventTitle}.\nApply here: ${decodeURIComponent(url)}`;
  const location = decodeURIComponent(venue);
  
  let dateParam = '';
  if (deadline) {
    const d = new Date(deadline);
    const startStr = d.toISOString().replace(/-|:|\.\d\d\d/g, "");
    dateParam = `&dates=${startStr}/${startStr}`;
  }

  const gcalUrl = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${encodeURIComponent(eventTitle + ' - Deadline')}&details=${encodeURIComponent(eventDetails)}&location=${encodeURIComponent(location)}${dateParam}`;
  window.open(gcalUrl, '_blank');
};

// --- Event Listeners ---
function initEventListeners() {
  // Search Input with Debounce
  let searchTimeout;
  elements.searchInput.addEventListener('input', (e) => {
    clearTimeout(searchTimeout);
    elements.clearSearchBtn.style.display = e.target.value ? 'block' : 'none';
    searchTimeout = setTimeout(() => {
      state.filters.search = e.target.value;
      applyFilters();
    }, 200);
  });

  elements.clearSearchBtn.addEventListener('click', () => {
    elements.searchInput.value = '';
    elements.clearSearchBtn.style.display = 'none';
    state.filters.search = '';
    applyFilters();
  });

  // Mode Tabs
  elements.modeTabs.forEach(tab => {
    tab.addEventListener('click', () => {
      elements.modeTabs.forEach(t => t.classList.remove('active'));
      tab.classList.add('active');
      state.filters.mode = tab.dataset.mode;
      applyFilters();
    });
  });

  // City Dropdown
  elements.citySelect.addEventListener('change', (e) => {
    state.filters.city = e.target.value;
    applyFilters();
  });

  // Sort Dropdown
  elements.sortSelect.addEventListener('change', (e) => {
    state.filters.sort = e.target.value;
    applyFilters();
  });

  // Tag Pills
  elements.tagsContainer.addEventListener('click', (e) => {
    if (e.target.classList.contains('tag-pill')) {
      document.querySelectorAll('.tag-pill').forEach(p => p.classList.remove('active'));
      e.target.classList.add('active');
      state.filters.tag = e.target.dataset.tag;
      applyFilters();
    }
  });

  // Reset Button
  elements.resetFiltersBtn.addEventListener('click', resetAllFilters);

  // Submit Modal
  elements.openSubmitModalBtn.addEventListener('click', () => {
    elements.submitModal.classList.add('open');
  });

  const closeModal = () => elements.submitModal.classList.remove('open');
  elements.closeSubmitModalBtn.addEventListener('click', closeModal);
  elements.cancelSubmitModalBtn.addEventListener('click', closeModal);
  elements.submitModal.addEventListener('click', (e) => {
    if (e.target === elements.submitModal) closeModal();
  });

  // Handle Community Event Submission
  elements.submitEventForm.addEventListener('submit', (e) => {
    e.preventDefault();
    const newEvent = {
      source: "Community Submission",
      source_url: document.getElementById('eventUrl').value,
      title: document.getElementById('eventTitle').value,
      organizer: document.getElementById('eventOrganizer').value,
      mode: document.getElementById('eventMode').value,
      venue_address: document.getElementById('eventVenue').value,
      city: document.getElementById('eventMode').value === 'Online' ? 'Online' : document.getElementById('eventVenue').value.split(',')[0].trim(),
      banner_url: document.getElementById('eventBanner').value || 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
      deadline: document.getElementById('eventDeadline').value + 'T23:59:59Z',
      prize_pool: document.getElementById('eventPrize').value || 'TBA',
      tags: ["Student Hackathon", "Community"]
    };

    // Save to local storage for persistence across reloads
    const local = JSON.parse(localStorage.getItem('hackradar_user_submissions') || '[]');
    local.unshift(newEvent);
    localStorage.setItem('hackradar_user_submissions', JSON.stringify(local));

    state.hackathons.unshift(newEvent);
    updateMetrics();
    applyFilters();
    closeModal();
    elements.submitEventForm.reset();
    showToast(`🎉 "${newEvent.title}" submitted and added to your feed!`);
  });

  // Manual Sync Link
  elements.syncNowLink.addEventListener('click', (e) => {
    e.preventDefault();
    showToast("🔄 Re-syncing latest hackathon feeds...");
    loadHackathonData();
  });
}

function resetAllFilters() {
  state.filters.search = '';
  state.filters.mode = 'ALL';
  state.filters.city = 'ALL';
  state.filters.tag = 'ALL';
  state.filters.sort = 'deadline_asc';

  elements.searchInput.value = '';
  elements.clearSearchBtn.style.display = 'none';
  elements.citySelect.value = 'ALL';
  elements.sortSelect.value = 'deadline_asc';

  elements.modeTabs.forEach(t => t.classList.toggle('active', t.dataset.mode === 'ALL'));
  document.querySelectorAll('.tag-pill').forEach(p => p.classList.toggle('active', p.dataset.tag === 'ALL'));

  applyFilters();
}

function showToast(msg) {
  const t = elements.toast;
  t.textContent = msg;
  t.classList.add('show');
  setTimeout(() => {
    t.classList.remove('show');
  }, 3500);
}
